# This workflow will do a clean installation of node dependencies, cache/restore them and run tests across different versions of node
name: Pull Request into main

on:
  pull_request:
    branches: ["main"]
    types: [opened, reopened, synchronize] # default werte, aber für readability

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      #setup
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: "package.json"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      # lint
      - name: Run ESLint
        run: npm run lint
      # build
      - name: Build Android app
        run: eas build --platform android --profile apk --local --output ${{ github.workspace }}/app-release.apk
      # artifact publish
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.apk
