# This workflow will do a clean installation of node dependencies, cache/restore them and run tests across different versions of node

name: Pull Request into main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  install-format-lint:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Breta

    strategy:
      matrix:
        node-version: [20.x, 21.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Auto Commit formated code
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply formatting changes
        branch: ${{ github.head_ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Run ESLint
      run: npm run lint
    - name: Format Code with Prettier
      run: npm run format
    #- run: npm test
    # Comment to trigger a PR -> Pipelinerun