# This workflow will do a clean installation of node dependencies, cache/restore them and run tests across different versions of node

name: Pull Request into main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: 
  contents: write

jobs:
  install-format-lint:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Breta

    steps:
    - uses: actions/checkout@v3
    - run: ls -al && pwd
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        node-version-file: './Breta/package.json'
    - run: npm ci
    - name: Run ESLint
      run: npm run lint
    - name: Format Code with Prettier
      run: npm run format
    - name: Auto Commit formated code
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply formatting changes
        branch: ${{ github.head_ref }}
    #- run: npm test
    # Comment to trigger a PR -> Pipelinerun